name: Deploy zipped build to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm install

    # - name: Run automation scripts (line + format + test)
    #   run: npm run check

    - name: Build Vite app
      run: npm run build

    - name: Zip build folder
      run: zip -r dist.zip dist

    - name: Copy and deploy zipped build to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "dist.zip"   
        target: "/home/ec2-user/cicd"

    - name: SSH and unzip to Nginx html folder
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/cicd
          unzip -o dist.zip
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r /home/ec2-user/cicd/dist/* /usr/share/nginx/html/
